/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class CompensatedDelayAudioProcessorEditor : public gin::ProcessorEditor,
                                             private gin::Parameter::ParameterListener
{
public:
    CompensatedDelayAudioProcessorEditor (CompensatedDelayAudioProcessor&);
    ~CompensatedDelayAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;

private:
    void valueUpdated (gin::Parameter* param) override;
    
    CompensatedDelayAudioProcessor& proc;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (CompensatedDelayAudioProcessorEditor)
};
