/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class WaveLooperAudioProcessorEditor : public gin::GinAudioProcessorEditor
{
public:
    WaveLooperAudioProcessorEditor (WaveLooperAudioProcessor&);
    ~WaveLooperAudioProcessorEditor();

    //==============================================================================
    void resized() override;
    void refresh();

private:    
    WaveLooperAudioProcessor& proc;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (WaveLooperAudioProcessorEditor)
};
