/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class ABTesterAudioProcessorEditor  : public gin::GinAudioProcessorEditor
{
public:
    ABTesterAudioProcessorEditor (ABTesterAudioProcessor&);
    ~ABTesterAudioProcessorEditor();

    //==============================================================================
    void resized() override;

private:
    ABTesterAudioProcessor& processor;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ABTesterAudioProcessorEditor)
};
