/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"

using namespace juce::dsp;


#define PARAM_AB        "ab"
#define PARAM_LEVEL     "level"

class ABTesterAudioProcessorEditor;
//==============================================================================
/**
*/
class ABTesterAudioProcessor : public gin::GinProcessor
{
public:
    //==============================================================================
    ABTesterAudioProcessor();
    ~ABTesterAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    
private:
    Component::SafePointer<ABTesterAudioProcessorEditor> editor;

    LinearSmoothedValue<float> aVal;
    LinearSmoothedValue<float> bVal;
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ABTesterAudioProcessor)
};
