/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"

using namespace juce::dsp;

class PluginEditor;

#define PARAM_GAIN_L     "gain_l"
#define PARAM_GAIN_R     "gain_r"
#define PARAM_GAIN_S     "gain_s"
#define PARAM_CLIP       "clip"

//==============================================================================
/**
*/
class PluginProcessor : public gin::GinProcessor
{
public:
    //==============================================================================
    PluginProcessor();
    ~PluginProcessor() override;

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================    
private:
    LinearSmoothedValue<float> lVal;
    LinearSmoothedValue<float> sVal;
    LinearSmoothedValue<float> rVal;
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PluginProcessor)
};
