/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include <mutex>
#include "PluginEditor.h"

//==============================================================================
//==============================================================================
namespace
{
    juce::File userResourceRoot()
    {
       #if JUCE_MAC
        return juce::File::getSpecialLocation (juce::File::userHomeDirectory)
                  .getChildFile ("Library/Audio/Presets/SocaLabs/BitCrusher");
       #elif JUCE_WINDOWS
        return juce::File::getSpecialLocation (juce::File::userApplicationDataDirectory)
                  .getChildFile ("SocaLabs/BitCrusher");
       #else
        return juce::File::getSpecialLocation (juce::File::userApplicationDataDirectory)
                  .getChildFile ("SocaLabs/BitCrusher");
       #endif
    }

    juce::File systemResourceRoot()
    {
       #if JUCE_MAC
        return juce::File ("/Library/Audio/Presets/SocaLabs/BitCrusher");
       #elif JUCE_WINDOWS
        return juce::File::getSpecialLocation (juce::File::commonApplicationDataDirectory)
                  .getChildFile ("SocaLabs/BitCrusher");
       #else
        return juce::File ("/usr/share/SocaLabs/BitCrusher");
       #endif
    }

    std::variant<float, juce::String> onOffTextFunction (const gin::Parameter&, const std::variant<float, juce::String>& in)
    {
        if (auto v = std::get_if<float> (&in))
            return juce::String (*v > 0.0f ? "On" : "Off");

        auto t = std::get<juce::String> (in).trim();
        if (t.equalsIgnoreCase ("On"))  return 1.0f;
        if (t.equalsIgnoreCase ("Off")) return 0.0f;
        return t.getFloatValue();
    }

    std::variant<float, juce::String> freqTextFunction (const gin::Parameter&, const std::variant<float, juce::String>& in)
    {
        if (auto v = std::get_if<float> (&in))
        {
            if (*v >= 1000.0f)
                return juce::String (*v / 1000.0f, 1) + " kHz";

            return juce::String (juce::roundToInt (*v)) + " Hz";
        }

        auto t = std::get<juce::String> (in).trim();
        auto freq = t.getFloatValue();
        if (t.endsWithIgnoreCase ("kHz") || (! t.endsWithIgnoreCase ("Hz") && freq < 30.0f))
            freq *= 1000.0f;
        return freq;
    }
}

static gin::ProcessorOptions createProcessorOptions()
{
    return gin::ProcessorOptions()
        .withMidiLearn();
}

// If the shared CrashReporter is installed, launch it once per process (on the
// first plugin instance) so it can scan and upload any crash from last session.
static void launchCrashReporterOnce()
{
    static std::once_flag flag;
    std::call_once (flag, []
    {
       #if JUCE_MAC
        juce::File app ("/Library/Application Support/Rabien Software/Crash Reporter/CrashReporter.app");
       #elif JUCE_WINDOWS
        auto app = juce::File::getSpecialLocation (juce::File::globalApplicationsDirectory)
                       .getChildFile ("Rabien Software").getChildFile ("Crash Reporter").getChildFile ("CrashReporter.exe");
       #else
        juce::File app;
       #endif

        if (app.exists())
            juce::Process::openDocument (app.getFullPathName(), {});
    });
}

BitCrusherAudioProcessor::BitCrusherAudioProcessor()
    : gin::Processor (false, createProcessorOptions())
{
    launchCrashReporterOnce();

    fifo.setSize (2, 44100);

    bits  = addExtParam ("bits",  "Bits",  "", "",   {  1.0f,    16.0f, 0.0f, 1.0f },    16.0f, 0.1f);
    rate  = addExtParam ("rate",  "Rate",  "", "Hz", {500.0f, 48000.0f, 0.0f, 0.3f }, 48000.0f, 0.1f, freqTextFunction);
    dirty = addExtParam ("dirty", "Dirty", "", "",   {  0.0f,     1.0f, 1.0f, 1.0f },     0.0f, 0.0f, onOffTextFunction);

    init();
}

BitCrusherAudioProcessor::~BitCrusherAudioProcessor()
{
}

//==============================================================================
void BitCrusherAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    gin::Processor::prepareToPlay (sampleRate, samplesPerBlock);

    crusher.setSampleRate (sampleRate);
    setLatencySamples (crusher.getLatencySamples());
}

void BitCrusherAudioProcessor::reset()
{
    gin::Processor::reset();

    crusher.reset();
}

void BitCrusherAudioProcessor::releaseResources()
{
}

void BitCrusherAudioProcessor::processBlock (juce::AudioSampleBuffer& buffer, juce::MidiBuffer& midi)
{
    if (midiLearn)
        midiLearn->processBlock (midi, buffer.getNumSamples());

    int numSamples = buffer.getNumSamples();

    crusher.setParams (bits->getProcValue (numSamples),
                       rate->getProcValue (numSamples),
                       dirty->getProcValue (numSamples) > 0.5f);

    crusher.process (buffer);

    if (getLatencySamples() != crusher.getLatencySamples())
        setLatencySamples (crusher.getLatencySamples());

    gin::ScratchBuffer fifoData (2, numSamples);
    for (int ch = 0; ch < 2; ch++)
        juce::FloatVectorOperations::copy (fifoData.getWritePointer (ch),
                                           buffer.getReadPointer (std::min (ch, buffer.getNumChannels() - 1)),
                                           numSamples);

    if (fifo.getFreeSpace() >= numSamples)
        fifo.write (fifoData);
}

//==============================================================================
bool BitCrusherAudioProcessor::hasEditor() const
{
    return true;
}

juce::AudioProcessorEditor* BitCrusherAudioProcessor::createEditor()
{
    return new BitCrusherAudioProcessorEditor (*this);
}

//==============================================================================
// This creates new instances of the plugin..
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new BitCrusherAudioProcessor();
}
//==============================================================================
juce::File BitCrusherAudioProcessor::getProgramDirectory()
{
    auto dir = userResourceRoot().getChildFile ("Presets");
    if (! dir.isDirectory())
        dir.createDirectory();
    return dir;
}

juce::Array<juce::File> BitCrusherAudioProcessor::getFactoryProgramDirectories()
{
    return { systemResourceRoot().getChildFile ("Presets") };
}
