/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <random>

using namespace gin;

//==============================================================================
String abTextFunction (const Parameter&, float v)
{
    return v > 0.0f ? "A" : "B";
}

//==============================================================================
AddInvertAudioProcessor::AddInvertAudioProcessor()
{
    //==============================================================================
}

AddInvertAudioProcessor::~AddInvertAudioProcessor()
{
}

//==============================================================================
void AddInvertAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
}

void AddInvertAudioProcessor::releaseResources()
{
}

void AddInvertAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer&)
{
    const int numSamples = buffer.getNumSamples();
    
    float* aL = buffer.getWritePointer (0);
    float* aR = buffer.getWritePointer (1);
    float* bL = buffer.getWritePointer (2);
    float* bR = buffer.getWritePointer (3);

    FloatVectorOperations::addWithMultiply (aL, bL, -1.0f, numSamples);
    FloatVectorOperations::addWithMultiply (aR, bR, -1.0f, numSamples);
    
    if (editor)
    {
        AudioSampleBuffer outputBuffer (buffer.getArrayOfWritePointers(), 2, numSamples);        
        editor->scope.addSamples (outputBuffer);
    }
}

//==============================================================================
bool AddInvertAudioProcessor::hasEditor() const
{
    return true;
}

AudioProcessorEditor* AddInvertAudioProcessor::createEditor()
{
    editor = new AddInvertAudioProcessorEditor (*this);
    return editor;
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new AddInvertAudioProcessor();
}
