/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class AddInvertAudioProcessorEditor  : public gin::GinAudioProcessorEditor
{
public:
    AddInvertAudioProcessorEditor (AddInvertAudioProcessor&);
    ~AddInvertAudioProcessorEditor();

    //==============================================================================
    void resized() override;
    
    drow::TriggeredScope scope;

private:
    AddInvertAudioProcessor& processor;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (AddInvertAudioProcessorEditor)
};
