/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "slCommon.h"

//==============================================================================
/**
*/
class slToneAudioProcessorEditor  : public slAudioProcessorEditor
{
public:
    slToneAudioProcessorEditor (slToneAudioProcessor&);
    ~slToneAudioProcessorEditor();

    //==============================================================================
    void resized() override;

    drow::TriggeredScope scope;

private:
    slToneAudioProcessor& processor;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (slToneAudioProcessorEditor)
};
