/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class slToneAudioProcessorEditor  : public gin::GinAudioProcessorEditor
{
public:
    slToneAudioProcessorEditor (slToneAudioProcessor&);
    ~slToneAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;

    drow::TriggeredScope scope;

private:
    slToneAudioProcessor& toneProcessor;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (slToneAudioProcessorEditor)
};
