#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Compressor.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Compressor.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Compressor.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Compressor.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/Compressor/Presets"
exit 0
