#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/PitchTrack.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/PitchTrack.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/PitchTrack.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/PitchTrack.clap"

exit 0
