#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/AddInvert.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/AddInvert.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/AddInvert.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/AddInvert.clap"

exit 0
