#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Crossfeed.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Crossfeed.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Crossfeed.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Crossfeed.clap"

exit 0
