#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/ChannelMute.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/ChannelMute.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/ChannelMute.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/ChannelMute.clap"

exit 0
