#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/XYScope.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/XYScope.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/XYScope.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/XYScope.clap"

exit 0
