#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Limiter.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Limiter.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Limiter.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Limiter.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/Limiter/Presets"
exit 0
