#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/SimpleVerb.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/SimpleVerb.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/SimpleVerb.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/SimpleVerb.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/SimpleVerb/Presets"
exit 0
