#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/WaveLooper.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/WaveLooper.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/WaveLooper.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/WaveLooper.clap"

exit 0
