#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/ABTester.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/ABTester.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/ABTester.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/ABTester.clap"

exit 0
