#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/MidiLooper.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/MidiLooper.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/MidiLooper.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/MidiLooper.clap"

exit 0
