#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Oscilloscope.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Oscilloscope.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Oscilloscope.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Oscilloscope.clap"

exit 0
