#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/StereoProcessor.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/StereoProcessor.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/StereoProcessor.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/StereoProcessor.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/StereoProcessor/Presets"
exit 0
