#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Gate.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Gate.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Gate.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Gate.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/Gate/Presets"
exit 0
