#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Expander.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Expander.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Expander.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Expander.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/Expander/Presets"
exit 0
