#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Loudness.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Loudness.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Loudness.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Loudness.clap"

exit 0
