#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/ToneGenerator.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/ToneGenerator.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/ToneGenerator.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/ToneGenerator.clap"

exit 0
