#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Delay.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Delay.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Delay.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Delay.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/Delay/Presets"
exit 0
