#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/SpectrumAnalyzer.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/SpectrumAnalyzer.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/SpectrumAnalyzer.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/SpectrumAnalyzer.clap"

exit 0
