#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Maths.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Maths.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Maths.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Maths.clap"

exit 0
