#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/SampleDelay.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/SampleDelay.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/SampleDelay.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/SampleDelay.clap"

exit 0
