#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/StereoEnhancer.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/StereoEnhancer.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/StereoEnhancer.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/StereoEnhancer.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/StereoEnhancer/Presets"
exit 0
