#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/GraphicEQ.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/GraphicEQ.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/GraphicEQ.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/GraphicEQ.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/GraphicEQ/Presets"
exit 0
