#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/SFX8.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/SFX8.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/SFX8.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/SFX8.clap"

exit 0
