#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/VU.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/VU.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/VU.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/VU.clap"

exit 0
