#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/HugeGain.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/HugeGain.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/HugeGain.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/HugeGain.clap"

exit 0
