#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Correlation.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Correlation.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Correlation.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Correlation.clap"

exit 0
