#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/CompensatedDelay.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/CompensatedDelay.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/CompensatedDelay.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/CompensatedDelay.clap"

exit 0
