/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

using namespace gin;

//==============================================================================
ChannelMuteAudioProcessorEditor::ChannelMuteAudioProcessorEditor (ChannelMuteAudioProcessor& p)
    : GinAudioProcessorEditor (p), processor (p)
{
    addAndMakeVisible (&scope);
    
    for (Parameter* pp : p.getPluginParameters())
    {
        ParamComponent* pc;
        
        if (pp->isOnOff())
            pc = new Switch (pp);
        else
            pc = new Knob (pp);
        
        addAndMakeVisible (pc);
        controls.add (pc);
    }
    
    setGridSize (5, 2);
    
    scope.setNumChannels (2);
    scope.setNumSamplesPerPixel (2);
    scope.setVerticalZoomFactor (1.0f);
}

ChannelMuteAudioProcessorEditor::~ChannelMuteAudioProcessorEditor()
{
}

//==============================================================================
void ChannelMuteAudioProcessorEditor::resized()
{
    GinAudioProcessorEditor::resized();

    componentForId (PARAM_MUTE_L)->setBounds (getGridArea (0, 0));
    componentForId (PARAM_LEVEL_L)->setBounds (getGridArea (0, 1));
    componentForId (PARAM_MUTE_R)->setBounds (getGridArea (1, 0));
    componentForId (PARAM_LEVEL_R)->setBounds (getGridArea (1, 1));

    scope.setBounds (getGridArea (2, 0, 3, 2));
}
