/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "slCommon.h"
#include "XYScope.h"

//==============================================================================
/**
*/
class PluginEditor  : public slAudioProcessorEditor,
                      private slParameter::Listener
{
public:
    PluginEditor (PluginProcessor&);
    ~PluginEditor();

    //==============================================================================
    void resized() override;
    Rectangle<int> getGridArea (int x, int y, int w = 1, int h = 1) override;

    XYScope scope;

private:
    CriticalSection lock;
    void updateScope();
    void parameterChanged (slParameter*) override { updateScope(); }
    
    PluginProcessor& processor;
    
    TimeSliceThread thread { "timeSlice" };
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PluginEditor)
};
