/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class LimiterAudioProcessorEditor : public gin::ProcessorEditor,
                                    private gin::Parameter::Listener
{
public:
    LimiterAudioProcessorEditor (LimiterAudioProcessor&);
    ~LimiterAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;
    void parameterChanged (gin::Parameter* param) override;

private:
    LimiterAudioProcessor& proc;
    
    gin::DynamicsMeter meter {proc.limiter};
    gin::TriggeredScope scope {proc.fifo};
    
    gin::LevelMeter inputMeter {proc.limiter.getInputTracker()};
    gin::LevelMeter outputMeter {proc.limiter.getOutputTracker()};
    gin::LevelMeter reductionMeter {proc.limiter.getReductionTracker(), {-30, 0}};

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (LimiterAudioProcessorEditor)
};
