/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

using namespace gin;

//==============================================================================
PluginEditor::PluginEditor (PluginProcessor& p)
    : GinAudioProcessorEditor (p), proc (p)
{
    addAndMakeVisible (&scope);
    
    scope.setColour (drow::TriggeredScope::traceColourId + 0, Colours::white.overlaidWith (Colours::blue.withAlpha (0.3f)));
    scope.setColour (drow::TriggeredScope::traceColourId + 1, Colours::white.overlaidWith (Colours::yellow.withAlpha (0.3f)));
    
    for (Parameter* pp : p.getPluginParameters())
    {
        ParamComponent* pc;
        
        if (pp->getUid() == PARAM_TRIGGER_MODE || pp->getUid() == PARAM_TRIGGER_CHANNEL)
            pc = new Select (pp);
        else if (pp->isOnOff())
            pc = new Switch (pp);
        else
            pc = new Knob (pp);
        
        addAndMakeVisible (pc);
        controls.add (pc);
    }
    
    setGridSize (7, 4);
    makeResizable (getWidth(), getHeight(), 2000, 1500);
    
    scope.setNumChannels (p.getTotalNumInputChannels());
    
    for (auto pp : proc.getPluginParameters())
        pp->addListener (this);
    
    updateScope();
}

PluginEditor::~PluginEditor()
{
    for (auto pp : proc.getPluginParameters())
        pp->removeListener (this);
}

//==============================================================================

Rectangle<int> PluginEditor::getGridArea (int x, int y, int w, int h)
{
    return Rectangle<int> (getWidth() - inset - 2 * cx + x * cx, headerHeight + y * cy + inset, w * cx, h * cy);
}

void PluginEditor::resized()
{
    GinAudioProcessorEditor::resized();

    scope.setBounds (inset, headerHeight + inset, getWidth() - 2 * cx - inset, getHeight() - headerHeight - 2 * inset);
    
    componentForId (PARAM_SAMPLES_PER_PIXEL)->setBounds (getGridArea (0, 0));
    componentForId (PARAM_VERTICAL_ZOOM)->setBounds (getGridArea (0, 1));
    componentForId (PARAM_VERTICAL_OFFSET_L)->setBounds (getGridArea (0, 2));
    componentForId (PARAM_VERTICAL_OFFSET_R)->setBounds (getGridArea (0, 3));
    componentForId (PARAM_TRIGGER_CHANNEL)->setBounds (getGridArea (1, 0));
    componentForId (PARAM_TRIGGER_MODE)->setBounds (getGridArea (1, 1));
    componentForId (PARAM_TRIGGER_LEVEL)->setBounds (getGridArea (1, 2));
    componentForId (PARAM_TRIGGER_POS)->setBounds (getGridArea (1, 3));
}

void PluginEditor::updateScope()
{
    scope.setDrawTriggerPos (true);
    scope.setNumSamplesPerPixel (proc.parameterIntValue (PARAM_SAMPLES_PER_PIXEL));
    scope.setVerticalZoomFactor (proc.parameterValue (PARAM_VERTICAL_ZOOM));
    scope.setVerticalZoomOffset (proc.parameterValue (PARAM_VERTICAL_OFFSET_L), 0);
    scope.setVerticalZoomOffset (proc.parameterValue (PARAM_VERTICAL_OFFSET_R), 1);
    scope.setTriggerChannel (proc.parameterIntValue (PARAM_TRIGGER_CHANNEL));
    scope.setTriggerMode ((gin::TriggeredScope::TriggerMode)proc.parameterIntValue (PARAM_TRIGGER_MODE));
    scope.setTriggerLevel (proc.parameterValue (PARAM_TRIGGER_LEVEL));
    scope.setTriggerPos (proc.parameterValue (PARAM_TRIGGER_POS));
}
