/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "slCommon.h"

//==============================================================================
/**
*/
class slToneAudioProcessorEditor  : public slAudioProcessorEditor
{
public:
    slToneAudioProcessorEditor (slToneAudioProcessor&);
    ~slToneAudioProcessorEditor();

    //==============================================================================
    void resized() override;

private:
    slToneAudioProcessor& processor;
    
    OwnedArray<ParamComponent> controls;
    LevelMeter meter;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (slToneAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
