/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
slToneAudioProcessorEditor::slToneAudioProcessorEditor (slToneAudioProcessor& p)
    : slAudioProcessorEditor (&p), processor (p)
{
    for (slParameter* pp : p.getPluginParameters())
    {
        PluginSlider* ps = new PluginSlider (pp, Slider::LinearVertical, Slider::NoTextBox);
        ps->setSkewFactor (pp->getSkew());
        addAndMakeVisible (ps);
        sliders.add (ps);
    }
    
    setSize (600, 300);
}

slToneAudioProcessorEditor::~slToneAudioProcessorEditor()
{
}

//==============================================================================
void slToneAudioProcessorEditor::paint(Graphics& g)
{
    g.fillAll (Colours::white);
}

void slToneAudioProcessorEditor::resized()
{
    Rectangle<int> r = getLocalBounds().reduced (6);
    
    int w = r.getWidth() / sliders.size();
    
    for (PluginSlider* s : sliders)
        s->setBounds (r.removeFromLeft (w));
}
