/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
slToneAudioProcessorEditor::slToneAudioProcessorEditor (slToneAudioProcessor& p)
    : slAudioProcessorEditor (&p), processor (p)
{
    for (slParameter* pp : p.getPluginParameters())
    {
        Knob* k = new Knob (pp);
        
        addAndMakeVisible (k);
        sliders.add (k);
    }
    
    setSize (600, 150);
}

slToneAudioProcessorEditor::~slToneAudioProcessorEditor()
{
}

//==============================================================================
void slToneAudioProcessorEditor::paint(Graphics& g)
{
    g.fillAll (Colours::white);
}

void slToneAudioProcessorEditor::resized()
{
    Rectangle<int> r = getControlsArea();
    
    int w = r.getWidth() / sliders.size();
    
    for (auto s : sliders)
        s->setBounds (r.removeFromLeft (w));
}
