/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "slCommon.h"

#define PARAM_ENABLE        "enable"
#define PARAM_FREQ          "freq"
#define PARAM_SINE_LEVEL    "sine"
#define PARAM_TRI_LEVEL     "triangle"
#define PARAM_SAW_LEVEL     "saw"
#define PARAM_SQUARE_LEVEL  "square"
#define PARAM_NOISE_LEVEL   "noise"

//==============================================================================
/**
*/
class slToneAudioProcessor : public slProcessor
{
public:
    //==============================================================================
    slToneAudioProcessor();
    ~slToneAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================

private:
    ToneGen sine;
    ToneGen triangle;
    ToneGen saw;
    ToneGen square;
    WhiteGaussianNoise noise;

    LinearSmoothedValue<float> enableVal;
    LinearSmoothedValue<float> sineVal;
    LinearSmoothedValue<float> triangleVal;
    LinearSmoothedValue<float> sawVal;
    LinearSmoothedValue<float> squareVal;
    LinearSmoothedValue<float> noiseVal;
    
    AudioSampleBuffer scratch;
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (slToneAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
