/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "slCommon.h"
#include "dywapitchtrack.h"

//==============================================================================
/**
*/
class slPitchTrackAudioProcessor : public slProcessor
{
public:
    //==============================================================================
    slPitchTrackAudioProcessor();
    ~slPitchTrackAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    
    LevelTracker& getOutputLevel() { return outputLevel; }
    float getPitch() { return pitch; }

private:
    LevelTracker outputLevel {48.0};
    
    AudioSampleBuffer scratch, work;
    CircularAudioBuffer audioHistory;
    dywapitchtracker trackInfo;
    RollingAverage averager {20};
    int workSize = 0;
    float pitch = 0;
    double sampleRate = 0;
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (slPitchTrackAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
