/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
slPitchTrackAudioProcessorEditor::slPitchTrackAudioProcessorEditor (slPitchTrackAudioProcessor& p)
    : slAudioProcessorEditor (&p), processor (p), meter (p.getOutputLevel())
{
    addAndMakeVisible (&meter);
    addAndMakeVisible (&pitch);
    
    pitch.setJustificationType (Justification::centred);
    
    startTimerHz (4);
    
    setSize (600, 150);
}

slPitchTrackAudioProcessorEditor::~slPitchTrackAudioProcessorEditor()
{
}

//==============================================================================
void slPitchTrackAudioProcessorEditor::paint(Graphics& g)
{
    g.fillAll (Colours::white);
}

void slPitchTrackAudioProcessorEditor::resized()
{
    Rectangle<int> r = getControlsArea();
    
    meter.setBounds (r.removeFromRight (15));
    pitch.setBounds (r);
}

void slPitchTrackAudioProcessorEditor::timerCallback()
{
    if (processor.getPitch() != lastPitch)
    {
        lastPitch = processor.getPitch();
        pitch.setText (String::formatted ("%.1f Hz", lastPitch), dontSendNotification);
    }
}