/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "slCommon.h"

//==============================================================================
/**
*/
class slPitchTrackAudioProcessorEditor : public slAudioProcessorEditor,
                                         private Timer
{
public:
    slPitchTrackAudioProcessorEditor (slPitchTrackAudioProcessor&);
    ~slPitchTrackAudioProcessorEditor();

    //==============================================================================
    void resized() override;
    void paint(Graphics& g) override;
    void timerCallback() override;

private:
    slPitchTrackAudioProcessor& processor;
    
    float lastPitch = -1;
    Label pitch;
    LevelMeter meter;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (slPitchTrackAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
