/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
PluginEditor::PluginEditor (PluginProcessor& p)
    : slAudioProcessorEditor (p), processor (p)
{
    addAndMakeVisible (&scope);
    
    setGridSize (7, 2);
    
    scope.setNumSamplesPerPixel (2);
    scope.setVerticalZoomFactor (1.0f);
    
    scope.setNumChannels (p.getTotalNumInputChannels());
}

PluginEditor::~PluginEditor()
{
}

//==============================================================================
void PluginEditor::resized()
{
    slAudioProcessorEditor::resized();

    scope.setBounds (getGridArea (1, 0, 3, 2));
}
