/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <random>

//==============================================================================
String onOffTextFunction (const slParameter& p)
{
    return p.getUserValue() > 0.0f ? "On" : "Off";
}

//==============================================================================
PluginProcessor::PluginProcessor()
{
    addPluginParameter (new slParameter (PARAM_SAMPLES_PER_PIXEL,       "Samp/px",       "", "",     1.0f,   48.0f,  1.0f,    1.0f, 1.0f));
    addPluginParameter (new slParameter (PARAM_VERTICAL_ZOOM,           "Zoom",          "", "",     0.25f,  100.0f, 0.0f,    1.0f, 1.0f));
    addPluginParameter (new slParameter (PARAM_TRIGGER_CHANNEL,         "Chan",          "", "",     -1.0f,  1.0f,   1.0f,    0.0f, 1.0f));
    addPluginParameter (new slParameter (PARAM_TRIGGER_MODE,            "Mode",          "", "",     0.0f,   2.0f,   1.0f,    1.0f, 1.0f));
    addPluginParameter (new slParameter (PARAM_TRIGGER_LEVEL,           "Level",         "", "",     -1.0f,  1.0f,   0.0f,    0.0f, 1.0f));
}

PluginProcessor::~PluginProcessor()
{
}

//==============================================================================
void PluginProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
}

void PluginProcessor::releaseResources()
{
}

void PluginProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer&)
{
    if (editor)
        editor->scope.addSamples (buffer);
}

//==============================================================================
bool PluginProcessor::hasEditor() const
{
    return true;
}

AudioProcessorEditor* PluginProcessor::createEditor()
{
    editor = new PluginEditor (*this);
    return editor;
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new PluginProcessor();
}
