/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
PitchTrackAudioProcessorEditor::PitchTrackAudioProcessorEditor (PitchTrackAudioProcessor& p)
    : GinAudioProcessorEditor (p), proc (p), meter (p.getOutputLevel())
{
    addAndMakeVisible (&meter);
    addAndMakeVisible (&pitch);
    
    pitch.setJustificationType (Justification::centred);
    
    startTimerHz (4);
    
    setSize (600, 150);
}

PitchTrackAudioProcessorEditor::~PitchTrackAudioProcessorEditor()
{
}

//==============================================================================
void PitchTrackAudioProcessorEditor::paint(Graphics& g)
{
    g.fillAll (Colours::white);
}

void PitchTrackAudioProcessorEditor::resized()
{
    Rectangle<int> r = getControlsArea();
    
    meter.setBounds (r.removeFromRight (15));
    pitch.setBounds (r);
}

void PitchTrackAudioProcessorEditor::timerCallback()
{
    if (proc.getPitch() != lastPitch)
    {
        lastPitch = proc.getPitch();
        pitch.setText (String::formatted ("%.1f Hz", lastPitch), dontSendNotification);
        
        DBG(lastPitch);
    }
}
