/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "UIComponents.h"

//==============================================================================
/**
*/
class SFXAudioProcessorEditor : public gin::GinAudioProcessorEditor
{
public:
    SFXAudioProcessorEditor (SFXAudioProcessor&);
    ~SFXAudioProcessorEditor();

    //==============================================================================
    void resized() override;
    void paint (Graphics& g) override;
    void refresh();

private:    
    SFXAudioProcessor& processor;

    PadGridComponent padGrid {processor};
    ParamComponent params {processor};
    Image logo;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SFXAudioProcessorEditor)
};
