/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class SampleDelayAudioProcessorEditor : public gin::GinAudioProcessorEditor,
                                        private gin::Parameter::Listener
{
public:
    SampleDelayAudioProcessorEditor (SampleDelayAudioProcessor&);
    ~SampleDelayAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;

private:
    void parameterChanged (gin::Parameter* param) override;
    
    SampleDelayAudioProcessor& proc;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SampleDelayAudioProcessorEditor)
};
