/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
sl3AMAudioProcessorEditor::sl3AMAudioProcessorEditor (sl3AMAudioProcessor& p)
    : slAudioProcessorEditor (&p), processor (p), meter (p.getOutputLevel())
{
    for (slParameter* pp : p.getPluginParameters())
    {
        Knob* k = new Knob (pp);
        
        addAndMakeVisible (k);
        controls.add (k);
    }
    
    addAndMakeVisible (&meter);
    
    setSize (600, 150);
}

sl3AMAudioProcessorEditor::~sl3AMAudioProcessorEditor()
{
}

//==============================================================================
void sl3AMAudioProcessorEditor::paint(Graphics& g)
{
    g.fillAll (Colours::white);
}

void sl3AMAudioProcessorEditor::resized()
{
    Rectangle<int> r = getControlsArea();
    
    meter.setBounds (r.removeFromRight (15));
    
    int w = r.getWidth() / controls.size();
    
    for (auto c : controls)
        c->setBounds (r.removeFromLeft (w));
}
