/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "slCommon.h"

//==============================================================================
/**
*/
class sl3AMAudioProcessorEditor  : public slAudioProcessorEditor
{
public:
    sl3AMAudioProcessorEditor (sl3AMAudioProcessor&);
    ~sl3AMAudioProcessorEditor();

    //==============================================================================
    void resized() override;
    void paint(Graphics& g) override;

private:
    sl3AMAudioProcessor& processor;
    
    OwnedArray<ParamComponent> controls;
    LevelMeter meter;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (sl3AMAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
