/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "slCommon.h"

#define PARAM_ENABLE    "enable"

//==============================================================================
/**
*/
class sl3AMAudioProcessor : public slProcessor
{
public:
    //==============================================================================
    sl3AMAudioProcessor();
    ~sl3AMAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    
    LevelTracker& getOutputLevel() { return outputLevel; }

private:
    ScopedPointer<Synthesiser> synth;
    
    LevelTracker outputLevel {48.0};

    LinearSmoothedValue<float> enableVal;
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (sl3AMAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
