/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"

#include "FormulaSynth.h"

using namespace juce::dsp;

class FormulaAudioProcessorEditor;
//==============================================================================
/**
*/
class FormulaAudioProcessor : public gin::GinProcessor
{
public:
    //==============================================================================
    FormulaAudioProcessor();
    ~FormulaAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    
private:
    Component::SafePointer<FormulaAudioProcessorEditor> editor;
    
    FormulaSynth formulaSynth;
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (FormulaAudioProcessor)
};
