/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

using namespace gin;

//==============================================================================
FormulaAudioProcessorEditor::FormulaAudioProcessorEditor (FormulaAudioProcessor& p)
    : GinAudioProcessorEditor (p), processor (p)
{
    addAndMakeVisible (&scope);
    
    setGridSize (4, 2);
    
    scope.setNumChannels (2);
    scope.setNumSamplesPerPixel (2);
    scope.setVerticalZoomFactor (1.0f);
}

FormulaAudioProcessorEditor::~FormulaAudioProcessorEditor()
{
}

//==============================================================================
void FormulaAudioProcessorEditor::resized()
{
    GinAudioProcessorEditor::resized();

    scope.setBounds (getGridArea (0, 0, 4, 2));
}
