/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"

#include "FormulaSynth.h"

using namespace juce::dsp;

#define PARAM_OSC1_ENABLE   "osc1enable"
#define PARAM_OSC2_ENABLE   "osc2enable"
#define PARAM_OSC3_ENABLE   "osc3enable"

#define PARAM_ATTACK        "attack"
#define PARAM_DECAY         "decay"
#define PARAM_SUSTAIN       "sustain"
#define PARAM_RELEASE       "release"
#define PARAM_VELOCITY      "velocity"

#define PARAM_FLT_ATTACK    "flt_attack"
#define PARAM_FLT_DECAY     "flt_decay"
#define PARAM_FLT_SUSTAIN   "flt_sustain"
#define PARAM_FLT_RELEASE   "flt_release"
#define PARAM_FLT_FREQ      "flt_freq"
#define PARAM_FLT_RES       "flt_res"
#define PARAM_FLT_AMOUNT    "flt_amount"
#define PARAM_FLT_KEY       "flt_key"
#define PARAM_FLT_VELOCITY  "flt_velocity"


class FormulaAudioProcessorEditor;
//==============================================================================
/**
*/
class FormulaAudioProcessor : public gin::GinProcessor
{
public:
    //==============================================================================
    FormulaAudioProcessor();
    ~FormulaAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    String getOscFormula (int idx);
    void setOscFormula (int idx, String formula);
    
private:
    void stateUpdated() override;
    void updateState() override;
    void refreshFormulas();
    
    String formulas[3];
    FormulaSynth formulaSynth;

    Component::SafePointer<FormulaAudioProcessorEditor> editor;
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (FormulaAudioProcessor)
};
