/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class MathsAudioProcessorEditor : public gin::GinAudioProcessorEditor,
                                  private TextEditor::Listener
{
public:
    MathsAudioProcessorEditor (MathsAudioProcessor&);
    ~MathsAudioProcessorEditor();

    //==============================================================================
    void resized() override;

private:
    void textEditorReturnKeyPressed (TextEditor&) override;
    void textEditorEscapeKeyPressed (TextEditor&) override;
    void textEditorFocusLost (TextEditor&) override;
    
    MathsAudioProcessor& processor;
    TextEditor l, r;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MathsAudioProcessorEditor)
};
