/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class MathsAudioProcessorEditor : public gin::GinAudioProcessorEditor,
                                  private TextEditor::Listener
{
public:
    MathsAudioProcessorEditor (MathsAudioProcessor&);
    ~MathsAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;
    void refresh();

private:
    void textEditorReturnKeyPressed (TextEditor&) override;
    void textEditorEscapeKeyPressed (TextEditor&) override;
    void textEditorFocusLost (TextEditor&) override;
    
    MathsAudioProcessor& mathsProcessor;
    TextEditor l, r;
    Label lLabel { "", "L out:" };
    Label rLabel { "", "R out:" };
    Label lError, rError;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MathsAudioProcessorEditor)
};
