/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class EchoAudioProcessorEditor : public gin::GinAudioProcessorEditor,
                                 private gin::Parameter::Listener
{
public:
    EchoAudioProcessorEditor (EchoAudioProcessor&);
    ~EchoAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;

private:
    void parameterChanged (gin::Parameter* param) override;
    
    EchoAudioProcessor& proc;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (EchoAudioProcessorEditor)
};
