/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class ABTesterAudioProcessorEditor  : public gin::ProcessorEditor
{
public:
    ABTesterAudioProcessorEditor (ABTesterAudioProcessor&);
    ~ABTesterAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;

private:
    ABTesterAudioProcessor& abProcessor;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ABTesterAudioProcessorEditor)
};
