/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

using namespace gin;

//==============================================================================
ABTesterAudioProcessorEditor::ABTesterAudioProcessorEditor (ABTesterAudioProcessor& p)
    : GinAudioProcessorEditor (p), processor (p)
{
    for (Parameter* pp : p.getPluginParameters())
    {
        ParamComponent* pc;
        
        if (pp->isOnOff())
            pc = new Switch (pp);
        else
            pc = new Knob (pp);
        
        addAndMakeVisible (pc);
        controls.add (pc);
    }
    
    setGridSize (4, 1);
}

ABTesterAudioProcessorEditor::~ABTesterAudioProcessorEditor()
{
}

//==============================================================================
void ABTesterAudioProcessorEditor::resized()
{
    GinAudioProcessorEditor::resized();

    componentForId (PARAM_AB)->setBounds (getGridArea (1, 0));
    componentForId (PARAM_LEVEL)->setBounds (getGridArea (2, 0));
}
