name: Build macOS
on:
  push:
    branches:
      - master
      - release
jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: "Run script"
        run: |
          export OS="mac"
          ./ci/build.sh
        shell: bash
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          INSTALLER: ${{ secrets.INSTALLER }}
          APPLE_PASS: ${{ secrets.APPLE_PASS }}
          APPLE_USER: ${{ secrets.APPLE_USER }}
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: ci/bin/*.zip
          retention-days: 30