/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

using namespace gin;

//==============================================================================
SFXAudioProcessorEditor::SFXAudioProcessorEditor (SFXAudioProcessor& p)
    : GinAudioProcessorEditor (p), processor (p)
{
    addAndMakeVisible (padGrid);
    addAndMakeVisible (params);

    setGridSize (10, 4);
}

SFXAudioProcessorEditor::~SFXAudioProcessorEditor()
{
}

//==============================================================================
void SFXAudioProcessorEditor::refresh()
{
}

void SFXAudioProcessorEditor::resized()
{
    GinAudioProcessorEditor::resized();

    auto rc = getFullGridArea();

    padGrid.setBounds (rc.removeFromLeft (rc.getHeight()));
    params.setBounds (rc);
}

