/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

using namespace gin;

//==============================================================================
SFXAudioProcessorEditor::SFXAudioProcessorEditor (SFXAudioProcessor& p)
    : GinAudioProcessorEditor (p), processor (p)
{
    for (Parameter* pp : p.getPluginParameters())
    {
        auto* pc = new Knob (pp, false);
        addAndMakeVisible (pc);
        controls.add (pc);
    }
    
    setGridSize (9, 1);
}

SFXAudioProcessorEditor::~SFXAudioProcessorEditor()
{
}

//==============================================================================
void SFXAudioProcessorEditor::refresh()
{
}

void SFXAudioProcessorEditor::resized()
{
    GinAudioProcessorEditor::resized();
}

