/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <random>

using namespace gin;

#include "../../../module/bfxr/PinkNumber.h"
#include "../../../module/bfxr/SfxrParams.h"
#include "../../../module/bfxr/SfxrSynth.h"
//==============================================================================
SFXAudioProcessor::SFXAudioProcessor()
{
}

SFXAudioProcessor::~SFXAudioProcessor()
{
}

//==============================================================================
void SFXAudioProcessor::stateUpdated()
{
}

void SFXAudioProcessor::updateState()
{
}

//==============================================================================
void SFXAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
}

void SFXAudioProcessor::releaseResources()
{
}

void SFXAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer&)
{
    ScopedLock sl (lock);
    
    ScopedNoDenormals noDenormals;
}

//==============================================================================
bool SFXAudioProcessor::hasEditor() const
{
    return true;
}

AudioProcessorEditor* SFXAudioProcessor::createEditor()
{
    editor = new SFXAudioProcessorEditor (*this);
    return editor;
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new SFXAudioProcessor();
}
